use std::path::PathBuf;

use peridot_common::{HooksConfig, SecurityConfig, ToolResult};
use peridot_llm::Usage;
use serde::{Deserialize, Serialize};

/// User-interface event emitted by the harness run loop.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum AgentRunEvent {
    /// A bounded run started.
    RunStarted {
        /// Initial task text.
        task: String,
    },
    /// A model/tool turn started.
    TurnStarted {
        /// Zero-based turn index.
        turn_index: u32,
    },
    /// Assistant streaming began.
    AssistantStarted {
        /// Stream label for display.
        label: String,
    },
    /// Assistant text streamed.
    AssistantDelta {
        /// Text delta.
        delta: String,
    },
    /// Assistant output completed.
    AssistantFinished {
        /// Full assistant text.
        text: String,
    },
    /// Parsed model thinking text.
    Thinking {
        /// Thinking text.
        text: String,
    },
    /// Tool execution started.
    ToolStarted {
        /// Tool name.
        name: String,
        /// Tool parameters.
        parameters: serde_json::Value,
    },
    /// Tool execution finished.
    ToolFinished {
        /// Tool name.
        name: String,
        /// Tool result.
        result: ToolResult,
    },
    /// A tool needs explicit user approval before it can proceed.
    ApprovalRequested {
        /// Tool name.
        tool_name: String,
        /// Human-readable reason.
        reason: String,
        /// Parameters the tool was about to execute with.
        #[serde(default)]
        parameters: serde_json::Value,
    },
    /// Usage totals changed.
    UsageUpdated {
        /// Aggregated run usage.
        usage: Usage,
    },
    /// The harness entered recovery.
    Recovery {
        /// Recovery message.
        message: String,
    },
    /// The bounded run finished.
    Finished {
        /// Final run summary.
        summary: AgentRunSummary,
    },
    /// The run summary was saved for later resume.
    SessionSaved {
        /// Saved session id.
        session_id: String,
    },
    /// The run summary could not be saved.
    SessionSaveFailed {
        /// Intended session id.
        session_id: String,
        /// Failure message.
        message: String,
    },
    /// A model/tool turn finished (paired with [`AgentRunEvent::TurnStarted`]).
    TurnEnded {
        /// Zero-based turn index that just completed.
        turn_index: u32,
        /// Whether the turn's tool call reported success.
        success: bool,
    },
    /// The active plan was updated by a tool (e.g., the plan tool).
    PlanUpdated {
        /// Current ordered plan steps.
        steps: Vec<PlanStepUpdate>,
        /// Optional zero-based index of the currently active step.
        current: Option<u32>,
    },
    /// Run-level budget or turn-count guardrail changed.
    BudgetUpdated {
        /// Cost spent so far, in USD.
        cost_used: f64,
        /// Configured cost ceiling (None means unbounded).
        cost_limit: Option<f64>,
        /// Turns consumed so far.
        turns_used: u32,
        /// Configured turn ceiling (None means unbounded).
        turns_limit: Option<u32>,
    },
    /// Context-manager utilization changed.
    ContextUtilizationChanged {
        /// Tokens already in the context window.
        tokens_used: u64,
        /// Compaction threshold.
        threshold: u64,
    },
    /// MCP server status changed (one or more servers connected / disconnected).
    McpStatusChanged {
        /// Current server snapshot.
        servers: Vec<McpStatusUpdate>,
    },
    /// AGENTS.md rules loaded at session start.
    AgentsMdLoaded {
        /// Total parsed rule count.
        rule_count: u32,
        /// Origin file paths.
        paths: Vec<String>,
    },
    /// A hook fired with the carried outcome label.
    HookFired {
        /// Hook name.
        name: String,
        /// Hook category (lifecycle, tool, event, ...).
        category: String,
        /// Outcome label such as `allow`, `block`, or `ok`.
        outcome: String,
    },
    /// The active run was interrupted by an external cancellation signal.
    Interrupted {
        /// Stage name (model_call, tool_call, verification, ...).
        stage: String,
    },
    /// The Planner role (M-COM2) finished its pre-flight pass and produced a
    /// task plan that the Executor will see as a `PlanReminder` context entry.
    PlannerPlanReady {
        /// Markdown / plain-text plan generated by the planner agent.
        plan_text: String,
    },
}

/// One plan step update payload accompanying [`AgentRunEvent::PlanUpdated`].
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct PlanStepUpdate {
    /// Step label.
    pub label: String,
    /// Whether the step is marked done.
    pub done: bool,
}

/// One MCP server snapshot accompanying [`AgentRunEvent::McpStatusChanged`].
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct McpStatusUpdate {
    /// Server display name.
    pub name: String,
    /// Exposed tool count.
    pub tool_count: u32,
    /// Whether the server is currently connected.
    pub connected: bool,
}

/// Request for one agent turn.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AgentTurnRequest {
    /// Optional user input to append before the turn.
    pub user_input: Option<String>,
    /// Model name.
    pub model: String,
    /// Maximum output tokens.
    pub max_tokens: u32,
    /// Project root.
    pub project_root: PathBuf,
    /// Denied path prefixes.
    pub denied_paths: Vec<PathBuf>,
    /// Active hook definitions.
    pub hooks: HooksConfig,
    /// Active security and sandbox settings.
    pub security: SecurityConfig,
}

/// Outcome of one agent turn.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentTurnOutcome {
    /// Tool name that was invoked.
    pub tool_name: String,
    /// Tool result.
    pub tool_result: ToolResult,
    /// Provider usage for the turn.
    pub usage: Usage,
    /// Whether the task is complete.
    pub done: bool,
}

/// Request for a bounded agent run.
#[derive(Clone, Debug, PartialEq)]
pub struct AgentRunRequest {
    /// Initial task.
    pub task: String,
    /// Model name.
    pub model: String,
    /// Optional independent model used to verify goal completion.
    pub goal_checker_model: Option<String>,
    /// Maximum number of turns.
    pub max_turns: u32,
    /// Maximum output tokens per turn.
    pub max_tokens: u32,
    /// Maximum estimated cost for the run. Values <= 0 disable budget stopping.
    pub budget_usd: f64,
    /// Budget warning threshold percentage.
    pub budget_warning_pct: u8,
    /// Project root.
    pub project_root: PathBuf,
    /// Denied path prefixes.
    pub denied_paths: Vec<PathBuf>,
    /// Active hook definitions.
    pub hooks: HooksConfig,
    /// Active security and sandbox settings.
    pub security: SecurityConfig,
}

/// Reason a bounded run stopped.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub enum StopReason {
    /// The agent called agent_done.
    Done,
    /// The run paused because a tool needs explicit approval.
    ApprovalRequired,
    /// The run hit max turns.
    MaxTurns,
    /// The run hit its configured cost budget.
    Budget,
    /// The run was cancelled by an external interrupt.
    Interrupted,
}

/// Summary of a bounded agent run.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentRunSummary {
    /// Turn outcomes.
    pub turns: Vec<AgentTurnOutcome>,
    /// Aggregated usage.
    pub usage: Usage,
    /// Stop reason.
    pub stopped_reason: StopReason,
}
