"""Generate the Peridot deer mascot SVG + PNG from a hand-drawn pixel grid.

Each character of `GRID` represents one pixel; palette entries map character
codes to RGB hex colors. The script writes both:
  - resources/peridot.svg  (vector, used by the activity bar)
  - resources/peridot-icon.png  (256x256 raster, used by the marketplace)

Rerun whenever the grid below changes; the resulting files are checked in.
"""
from pathlib import Path
import cairosvg

# Palette — keep in sync with crates/peridot-tui/src/mascot/frames.rs.
PALETTE = {
    ".": None,             # transparent
    "D": "#365C1E",        # antler / outline dark green
    "G": "#85B240",        # body mid green
    "L": "#D2E882",        # body highlight light green
    "F": "#A8D352",        # face mid tone (between G and L)
    "J": "#287538",        # gem outline / deep peridot
    "C": "#5BD46E",        # gem core (bright)
    "S": "#E1FFD7",        # gem sparkle / eye-shine
    "W": "#F8FDE8",        # eye whites
    "K": "#1C1C20",        # eye pupil
    "N": "#FFB6C1",        # nose pink
    "M": "#5A381E",        # mouth / hoof dark
    "H": "#7A4F2C",        # hoof body
}

# 32 x 32. Read top-to-bottom, left-to-right. Edit freely.
GRID = """
................................
................D....D..D....D..
...............DDD..DDDDD....DD.
..............DDDD..DDDD......D.
..............DDD....DD.......D.
...............DD....DD......DD.
...............DD....DD.....DDD.
.............DDDDDDDDDDDD..DDDD.
............DLLLLLLLLLLLLDD.....
...........DLLLFFFFFFFFLLLLD....
..........DLLFFFFFFFFFFFFLLLD...
.........DLLFFFFJJJJFFFFFFLLLD..
.........DLFFFFJCCCCJFFFFFFFLD..
.........DLFFFJCCSSCJFFFFFFFLD..
.........DLFWWFJCCCJFWWFFFFFLD..
.........DLFWKWFJJJFWKWFFFFFLD..
.........DLFFWWFFFFFWWFFFFFFLD..
.........DLFFFFFFFFFFFFFFFFFLD..
..........DLFFFFFNNFFFFFFFFLD...
..........DLFFFFFMMFFFFFFFFLD...
...........DLLFFFFFFFFFFFLLD....
............DDLLLLLLLLLLLDD.....
.............DGGGGGGGGGGGD......
............DGGGGGGGGGGGGGD.....
...........DGGLLLGGCJGGLLGGD....
...........DGLLLLGCSCGLLLLGD....
...........DGLLGGJCJGGLLLGGD....
...........DGGGGGGGGGGGGGGGD....
...........DGGGDDGGGGDDGGGGD....
............DHHHD....DHHHD......
............DMHHD....DMHHD......
................................
"""


def parse_grid(text: str) -> list[list[str]]:
    rows = [row for row in text.splitlines() if row.strip()]
    if len(rows) != 32:
        raise SystemExit(f"expected 32 rows, got {len(rows)}")
    for index, row in enumerate(rows):
        if len(row) != 32:
            raise SystemExit(f"row {index} has {len(row)} columns, expected 32")
        for col, char in enumerate(row):
            if char not in PALETTE:
                raise SystemExit(f"row {index} col {col}: unknown palette char {char!r}")
    return [list(row) for row in rows]


def build_runs(rows: list[list[str]]):
    """Collapse horizontal runs of identical color into single <rect>s."""
    runs = []
    for y, row in enumerate(rows):
        x = 0
        while x < len(row):
            char = row[x]
            if char == "." or PALETTE[char] is None:
                x += 1
                continue
            run_x = x
            while x < len(row) and row[x] == char:
                x += 1
            runs.append((run_x, y, x - run_x, char))
    return runs


def render_svg(rows) -> str:
    runs = build_runs(rows)
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!-- Peridot Agent — pixel-art deer mascot (32x32).",
        "     Generated by scripts/render-mascot.py from the GRID literal.",
        "     Palette mirrors crates/peridot-tui/src/mascot/frames.rs. -->",
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" shape-rendering="crispEdges">',
    ]
    for x, y, width, char in runs:
        color = PALETTE[char]
        lines.append(
            f'  <rect x="{x}" y="{y}" width="{width}" height="1" fill="{color}"/>'
        )
    lines.append("</svg>")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    extension_dir = Path(__file__).resolve().parent.parent
    resources = extension_dir / "resources"
    rows = parse_grid(GRID)
    svg = render_svg(rows)
    svg_path = resources / "peridot.svg"
    svg_path.write_text(svg)
    cairosvg.svg2png(
        bytestring=svg.encode("utf-8"),
        write_to=str(resources / "peridot-icon.png"),
        output_width=256,
        output_height=256,
    )
    print(f"wrote {svg_path} ({svg_path.stat().st_size} bytes)")
    print(f"wrote {resources / 'peridot-icon.png'}")


if __name__ == "__main__":
    main()
